#################################
# APPLICATION CONFIG
#################################

#spring.config.import=optional:file:.env
#spring.config.import=optional:file:.env[.properties]
spring.config.import=optional:file:.env.properties

spring.application.name=${SPRING_APPLICATION_NAME}
server.address=0.0.0.0
server.port=8081

spring.jpa.properties.hibernate.default_schema=school

#################################
# DATABASE
#################################
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

#################################
# JPA / HIBERNATE
#################################
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
#spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL}
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_FORMAT_SQL}
spring.jpa.properties.hibernate.dialect=${SPRING_JPA_DIALECT}

#################################
# JWT CONFIG
#################################
jwt.secret=${JWT_SECRET}
jwt.access.expiration=${JWT_ACCESS_EXPIRATION}
jwt.refresh.expiration=${JWT_REFRESH_EXPIRATION}


spring.mail.host=${SPRING_MAIL_HOST}
spring.mail.port=${SPRING_MAIL_PORT}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=${SPRING_MAIL_SMTP_AUTH}
spring.mail.properties.mail.smtp.starttls.enable=${SPRING_MAIL_SMTP_STARTTLS}
spring.mail.from=${SPRING_MAIL_USERNAME}


spring.servlet.multipart.max-file-size=${SPRING_MAX_FILE_SIZE}
spring.servlet.multipart.max-request-size=${SPRING_MAX_REQUEST_SIZE}


spring.web.resources.static-locations=${SPRING_STATIC_LOCATIONS}
spring.mvc.static-path-pattern=${SPRING_STATIC_PATH}


cloud.aws.credentials.accessKey=${CLOUD_AWS_CREDENTIALS_ACCESSKEY}
cloud.aws.credentials.secretKey=${CLOUD_AWS_CREDENTIALS_SECRETKEY}
cloud.aws.region.static=${CLOUD_AWS_REGION_STATIC}
cloud.aws.s3.bucket=${CLOUD_AWS_S3_BUCKET}

#logging.level.com.zaxxer.hikari=DEBUG

app.frontend.onboarding-url=http://localhost:8081/modal